service: aws-node-project

frameworkVersion: '2'

plugins:
    - serverless-dynamodb-local   
    - serverless-offline          #No need for server
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
functions:
  hello:
    handler: handler.hello
    events:
     -http:
        path: first-endpoint
        method: GET
